### ISSUE TITLE
Error messages in HA Logs

### ISSUE THREAD

**Issue by willsmarthome** [plugwise/plugwise-beta#102]
After installing 2 error messages in 0.4.0 HA logging, see attachments.

Everything seems to work fine.

[040 error1 .txt](https://github.com/plugwise/plugwise-beta/files/4895748/040.error1.txt)

[040 error2.txt](https://github.com/plugwise/plugwise-beta/files/4895750/040.error2.txt)

**Comment by CoMPaTech** [comment]
Moving this back again, @bouwew and me looked at it and it looks like error01 and error02 both (eventually) point to what (in 0.4) was a missing exception, we'll be adding that.

**Comment by CoMPaTech** [comment]
@willsmarthome for reference/background it looks like fetching new data from the smile doesn't always work out, but instead of properly handling it (and informing HA about it) we missed the handling. Technically, we only catch missing out on correct XML data instead of also handling connection errors or timeouts.

**Comment by bouwew** [comment]
I'm seeing this one:
```
Log Details (ERROR)
Logger: Plugwise_Smile.Smile
Source: /usr/local/lib/python3.8/site-packages/Plugwise_Smile/Smile.py:319
First occurred: 8:34:39 PM (1 occurrences)
Last logged: 8:34:39 PM

Error sending command to Plugwise: /core/domain_objects
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/Plugwise_Smile/Smile.py", line 302, in request
    resp = await self.websession.get(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError
```
And this one too:
```
Log Details (ERROR)
Logger: custom_components.plugwise
Source: helpers/update_coordinator.py:165
Integration: Plugwise Beta (documentation)
First occurred: 8:34:39 PM (1 occurrences)
Last logged: 8:34:39 PM

Error fetching Smile data: Smile update failed
```

**Comment by bouwew** [comment]
I also see this one:
```
Logger: Plugwise_Smile.Smile
Source: /usr/local/lib/python3.8/site-packages/Plugwise_Smile/Smile.py:319
First occurred: September 4, 2020, 8:54:53 PM (17 occurrences)
Last logged: 6:40:43 AM

Error sending command to Plugwise: /core/domain_objects
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/Plugwise_Smile/Smile.py", line 302, in request
    resp = await self.websession.get(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer
```

**Comment by bouwew** [comment]
And this one:
```
Log Details (ERROR)
Logger: Plugwise_Smile.Smile
Source: /usr/local/lib/python3.8/site-packages/Plugwise_Smile/Smile.py:319
First occurred: 3:12:20 AM (2 occurrences)
Last logged: 9:05:47 AM

Error sending command to Plugwise: /core/domain_objects
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 494, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 526, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.1.102', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/Plugwise_Smile/Smile.py", line 302, in request
    resp = await self.websession.get(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 480, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 980, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 943, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.1.102:80 ssl:default [Connect call failed ('192.168.1.102', 80)]
```

Accompanied by this one:
```
Log Details (ERROR)
Logger: custom_components.plugwise
Source: helpers/update_coordinator.py:165
Integration: Plugwise Beta (documentation)
First occurred: September 4, 2020, 8:54:53 PM (18 occurrences)
Last logged: 9:05:47 AM

Error fetching Smile data: Smile update failed
```

**Comment by bouwew** [comment]
And finally, this one:
```
Log Details (ERROR)
Logger: Plugwise_Smile.Smile
Source: /usr/local/lib/python3.8/site-packages/Plugwise_Smile/Smile.py:340
First occurred: 3:12:30 AM (11 occurrences)
Last logged: 9:06:17 AM

Smile returns invalid XML for http://192.168.1.102:80
```

**Comment by bouwew** [comment]
Update: after removing the aiohttp.ClientError-exception from Plugwise_Smile the error-messages are short like to last one shown above. 

In the HA Core tesla-code there is a comment stating that "aiohttp"-errors are handled in the home assistant DeviceUpdateCoordinator-function, so, no need to have such exceptions in the Plugwise(_Smile)-code.

**Comment by bouwew** [comment]
Let's close, should be mostly solved as far as we can solve this.
Meaning, there will be only short error-messages shown in logs, no more quite long ones.
