### ISSUE TITLE
[BUG] Plugwise Notification related error in Logs

### ISSUE THREAD

**Issue by bouwew** [plugwise/plugwise-beta#144]
**Describe the bug**
Error in logs:

**Evidence**
``` 
Logger: homeassistant
Source: custom_components/plugwise/binary_sensor.py:293
First occurred: 5:32:07 PM (285 occurrences)
Last logged: 7:54:46 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 119, in _handle_refresh_interval
    await self.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 193, in async_refresh
    update_callback()
  File "/config/custom_components/plugwise/binary_sensor.py", line 293, in _async_process_data
    self._attributes[f"{msg_type.upper()}_msg"].append(msg)
KeyError: 'WARNING_msg'
```

3. After the restart, at Developer Tools --> Logs, load the FULL HA LOG.
4. Upload relevant issues to a site like pastebin and copy the link here

**Expected behavior**

**Screenshots**

**Home Assistant (please complete the following information):**
 - Version: 1.0.0b2
 - Deployment: hassio in VM
 - Installed plugwise version: 'plugwise-beta]
 - Installed through: HACS

**Smile (please complete the following information):**
 - Sort of Smile: Adam
 - Firmware: 3.2.4

**Comment by bouwew** [comment]
Looks like there is a mismatch in the line 4 and last:
```
    def _async_process_data(self):
        """Update the entity."""
        for severity in SEVERITIES:
            self._attributes[f"{severity}_msg"] = []

        notify = self._api.notifications

        self._is_on = False
        self._icon = NO_NOTIFICATION_ICON

        if notify != {}:
            self._is_on = True
            self._icon = NOTIFICATION_ICON

            for notify_id, details in notify.items():
                for msg_type, msg in details.items():
                    if msg_type not in SEVERITIES:
                        msg_type = "other"

                    self._attributes[f"{msg_type.upper()}_msg"].append(msg)
```

Solution: change line 4 to: `self._attributes[f"{severity.upper()}_msg"] = []`
Or, remove `.upper()` from the last line.
