### ISSUE TITLE
System option to disable adding new devices not honored

### ISSUE THREAD

**Issue by brefra** [plugwise/plugwise-beta#174]
_Copied over from [this bug](https://github.com/plugwise/python-plugwise/issues/84) reported at python-plugwise_

**Describe the bug**
This message is shown in HA Core Logs:
```
Logger: root
Source: custom_components/plugwise/usb.py:94
Integration: Plugwise Beta (documentation)
First occurred: 11:33:49 (1 occurrences)
Last logged: 11:33:49

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/plugwise/stick.py", line 329, in scan_timeout_expired
    self.scan_callback()
  File "/config/custom_components/plugwise/usb.py", line 94, in discover_finished
    if config_entry.system_options.disable_new_entities:
AttributeError: 'ConfigEntry' object has no attribute 'system_options'
```
**Home Assistant Core (please complete the following information):**
 - Version: 2021.6.2
 - Deployment: Proxmox VM
 - Installed plugwise version: 0.15.0b0 + plugwise v0.10.0 (from testpypi)
 - Installed through 'HACS']

**Plugwise product (please complete the following information):**
 - Type: Stick
 - Firmware: NA

**Comment by brefra** [comment]
Resolved in release 0.14.7
