### ISSUE TITLE
[BUG] Anna (Unable to find referenced entities climate.anna) v0.20.0

### ISSUE THREAD

**Issue by malosaa** [plugwise/plugwise-beta#231]
**Describe the bug**
Anna has an error both v20 and v20.b0

**The errors**
```
Logger: homeassistant.helpers.service
Source: helpers/service.py:130
First occurred: 16:47:12 (3 occurrences)
Last logged: 16:47:12

Unable to find referenced entities climate.anna
```

```
Logger: homeassistant.config_entries
Source: custom_components/plugwise/gateway.py:101
Integration: Plugwise Beta (documentation)
First occurred: 16:46:51 (1 occurrences)
Last logged: 16:46:51

Error setting up entry Anna for plugwise
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 327, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/plugwise/__init__.py", line 16, in async_setup_entry
    return await async_setup_entry_gw(hass, entry)
  File "/config/custom_components/plugwise/gateway.py", line 101, in async_setup_entry_gw
    api.get_all_devices()
  File "/usr/local/lib/python3.9/site-packages/plugwise/smile.py", line 119, in get_all_devices
    self._all_device_data()
  File "/usr/local/lib/python3.9/site-packages/plugwise/smile.py", line 71, in _all_device_data
    data = self._get_device_data(dev_id)
  File "/usr/local/lib/python3.9/site-packages/plugwise/smile.py", line 205, in _get_device_data
    device_data = self._get_appliance_data(dev_id)
  File "/usr/local/lib/python3.9/site-packages/plugwise/helper.py", line 820, in _get_appliance_data
    and self._outdoor_temp > data["cooling_activation_outdoor_temperature"]
TypeError: '>' not supported between instances of 'NoneType' and 'float'
```

**Additional context**
 version v0.20.0

**Comment by malosaa** [comment]
i did reverd back to 19.8 that works good for now

**Comment by bouwew** [comment]
Sorry to hear that.
Hoe does your system look like? Does your Anna connect to an Elga?

**Comment by malosaa** [comment]
@bouwew 

no worries, i reverted back for now.
no the anna is connected with adam. 
But i only use anna for now.

regards

**Comment by bouwew** [comment]
Hmm, our README on the github and the HA Code Plugwise manual both clearly state NOT to load the Anna when there is an Adam. So please follow that advice.

**Comment by malosaa** [comment]
I never had a problem.. till the last release.

How do people do it when they have both like me ? 
So anna is not needed ? 
But Adam gives me the pressure and some other data, while i need the anna to start the heater when the livingroom is to cold.

**Comment by bouwew** [comment]
When you have both, as do I, the Adam becomes the "boss" of the system. The Anna turns into a kind of "dumber" temperature sensor with a display. You can still make changes on the Anna but the Adam picks these up and handles these changes.
So in the end the Adam starts the heater because that one is connected to your heater. And the Anna is connected to the Adam. If not, then you have wired your system incorrectly.

**Comment by bouwew** [comment]
Anyway, you should only load the Plugwise Adam integration. Anything that you manually change on the Anna will be shown via the Adam integration. 
You will see a `climate.anna` device when you only load the Adam integration.

**Comment by malosaa** [comment]
aah i understand now, i gonna test that out then.
As i only have an error on anna, as adam works good.

I let u know

**Comment by malosaa** [comment]
Yes i see the anna is detected by adam,
So i can disable anna plugin then, and use adam instead?

Regards

**Comment by malosaa** [comment]
You right, it works, but i get one message in my logs tho.
I really don't know where is coming from.
thats the adam device

```
Logger: homeassistant.helpers.script
Source: helpers/script.py:659
First occurred: February 6, 2022, 21:10:42 (162 occurrences)
Last logged: 10:47:24

Error in 'choose[0]' evaluation: In 'numeric_state': In 'numeric_state' condition: unknown entity sensor.openthermthermostat_temperature
Error in 'choose[1]' evaluation: In 'numeric_state': In 'numeric_state' condition: unknown entity sensor.openthermthermostat_temperature

```

**Comment by bouwew** [comment]
Ok great, glad to hear that it works.

This error is not related to the plugwise-beta integration. But I think this error originates from an automation?

**Comment by malosaa** [comment]
> Ok great, glad to hear that it works.
> 
> This error is not related to the plugwise-beta integration. But I think this error originates from an automation?

Yeah probably, but i can't find it.
I checked all the automations.

Is there a way to check what automation is causing it ?

**Comment by bouwew** [comment]
Well, the automation is connected to the `opentherm_thermostat`. That's the best I can do :)

I'm closing this issue. The misuse of the plugwise integration has been pointed out and has been corrected :)

**Comment by bouwew** [comment]
@malosaa We see this error at other systems, we don't fully understand why this happens.

You can help us by letting us know what kind of heating(/cooling) device is controlled by your Adam?
It is some kind of heatpump?

**Comment by malosaa** [comment]
> @malosaa We see this error at other systems, we don't fully understand why this happens.
> 
> You can help us by letting us know what kind of heating(/cooling) device is controlled by your Adam? It is some kind of heatpump?

I just attached the adam to my opentherm device, its no heatpump. (Nefit proline NXT)

I maybe need top open another topic for this:
As on homeseer, the plugin stefan made, the adamplugin had a lot more options to configure trough homeseer.
Like i could set it to WarmOntluchten/KoudOntluchten/verwarmen/uit  and i could turn on the ECO mode on and off.

I could not find these options, but can you implement them so i don't have to use the guy or use homeseer for it?
Regards

**Comment by bouwew** [comment]
Ok thanks. Would you mind sharing your xml-data from `http://<ip of your adam>/core/appliances`, please send to my email: bouwe "at" westerdijk "point" info 
I still don't fully understand why this happens in your system. I would like to understand it :)

For the other request, yes please create a separate issue (feature request).
There will be one problem though, I don't have most of these functions so I would not know how to implement them. Are you able to capture http-traffic from your pc to the Adam? If I can see what data the Adam-webpage sends when you make a change, that will help me implement the functions.
Another problem is, how to show the possibility of changing a value in the Core Frontend? I would need to investigate...

**Comment by malosaa** [comment]
> Ok thanks. Would you mind sharing your xml-data from `http://<ip of your adam>/core/appliances`, please send to my email: bouwe "at" westerdijk "point" info I still don't fully understand why this happens in your system. I would like to understand it :)
> 
> For the other request, yes please create a separate issue (feature request). There will be one problem though, I don't have most of these functions so I would not know how to implement them. Are you able to capture http-traffic from your pc to the Adam? If I can see what data the Adam-webpage sends when you make a change, that will help me implement the functions. Another problem is, how to show the possibility of changing a value in the Core Frontend? I would need to investigate...

Ok ill open another feature request. i will email you now
