### ISSUE TITLE
[BUG] Config flow could not be loaded | munch not installed

### ISSUE THREAD

**Issue by rottweilertje** [plugwise/plugwise-beta#244]
I'm not sure if this is a plugwise-beta responsibility or not, so if this is the wrong place to put this, feel free to point me in the right direction and close this issue.

**Describe the bug**
Configuring the plugin in HA Core gives an error when trying to install `Plugwise Beta` via HA Core Integrations. 
```
Config flow could not be loaded: [object Object]
```
Logs show that python package `munch` was not installed. 

**Home Assistant:**
 - Version: 2022.2.2
 - Deployment: on Kubernetes (microk8s) with image: homeassistant/home-assistant:2022.2.2 
 - Installed plugwise version: v0.21.2
 - Installed through 'HACS' as custom_component

**Fix**
Manually install `munch` from inside the container
```
$ pip install munch
```
But with containerized infrastructure that is not an optimal solution.

**Evidence**
Steps to reproduce 

1. Installing HACS
2. In HACS adding this repository as custom repository
3. In HA Core adding `Plugwise beta` as Integration
4. Click Configure in the Plugwise Beta integration

``` 
2022-03-04 16:25:42 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration plugwise which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-03-04 16:25:42 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-03-04 16:25:43 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing component custom_components.plugwise
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 547, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/plugwise/__init__.py", line 9, in <module>
    from .gateway import async_setup_entry_gw, async_unload_entry_gw
  File "/config/custom_components/plugwise/gateway.py", line 9, in <module>
    from plugwise.exceptions import InvalidAuthentication, PlugwiseException
  File "/config/deps/lib/python3.9/site-packages/plugwise/__init__.py", line 5, in <module>
    from plugwise.smile import Smile
  File "/config/deps/lib/python3.9/site-packages/plugwise/smile.py", line 12, in <module>
    from munch import Munch
  File "/config/deps/lib/python3.9/site-packages/munch/__init__.py", line 28, in <module>
    __version__ = pkg_resources.get_distribution('munch').version
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 466, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 342, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'munch' distribution was not found and is required by the application
```

```
/config # pip list | grep mu
aiomusiccast                     0.14.3
emulated-roku                    0.2.1
mullvad-api                      1.0.0
multidict                        5.2.0
mutagen                          1.45.1
mutesync                         0.0.1
pycmus                           0.1.1
```

**Comment by bouwew** [comment]
@rottweilertje As far as we know, everything is correct on the plugwise side: in `setup.py` we specify the "install_requires", `munch` is in that list. Looks like your environment doesn't pick up these install_requires correctly.

**Comment by rottweilertje** [comment]
Closing this issue with the following solution.

Apparently the HA image I was using:  `2022.2.2` didn't include `munch`
Bumping the HA image version to `2022.3.1` shows `munch` is installed out of the box and after going through the motions of installing HACS and the plugwise-beta plugin things work like a charm.

From what I understand from looking at the history of this and the native plugwise plugin it looks to me, it should have been in the originally used image already, but it wasn't and now it is, so all is well.

**Comment by CoMPaTech** [comment]
👍

**Comment by bouwew** [comment]
Ah yes, that makes sense, HA 2022.3.0 and newer versions contain the newest plugwise code linking to the plugwise-library with the install_require = munch. And because of this, munch is included in that image.

Anyway, the only other solution, installing munch manually, was also already found by you :)
I don't think there would be any other solutions for this problem, given the uniqueness of your system/installation.

**Comment by rottweilertje** [comment]
> I don't think there would be any other solutions for this problem, given the uniqueness of your system/installation.

I agree, after you mentioned it should already be installed as a dependency I reckoned I had to look at the image of HA instead of some install script used by HACS or so.
