### ISSUE TITLE
[BUG] climate.anna isnt loading

### ISSUE THREAD

**Issue by Proxx** [plugwise/plugwise-beta#245]
**Describe the bug**
climate.anna isnt loading due to error about unknown variable

**Evidence**
``` log
2022-03-11 01:39:25 DEBUG (MainThread) [custom_components.plugwise] Plugwise Anna updated
2022-03-11 01:39:25 DEBUG (MainThread) [custom_components.plugwise] Data: PlugwiseData(gateway={'smile_name': 'Anna', 'gateway_id': 'd5ad3b50d9774eb18612ebd0d65daac3', 'heater_id': None, 'cooling_present': False, 'notifications': {}}, devices={'d5ad3b50d9774eb18612ebd0d65daac3': {'class': 'gateway', 'fw': '4.2.1', 'hw': 'AME Smile 2.0 board', 'location': '869ad2f1e6474b2d829452069839b1f5', 'mac_address': 'D40FB201213D', 'model': 'Anna', 'name': 'Anna', 'vendor': 'Plugwise B.V.', 'binary_sensors': {'plugwise_notification': False}, 'sensors': {'outdoor_temperature': 6.5}}, 'a683c33cd6f04e15ab6eaede93c01644': {'class': 'thermostat', 'fw': '2018-02-08T11:15:53+01:00', 'hw': '6539-1301-5002', 'location': '0940dfa509a141728f2b3cd674b9cf08', 'mac_address': None, 'model': 'Anna', 'name': 'Anna', 'vendor': 'Plugwise', 'lower_bound': 4, 'upper_bound': 30, 'resolution': 0.1, 'preset_modes': ['vacation', 'no_frost', 'home', 'away', 'asleep'], 'active_preset': 'asleep', 'presets': {'vacation': [15.0, 28.0], 'no_frost': [10.0, 30.0], 'home': [20.0, 22.0], 'away': [18.0, 25.0], 'asleep': [17.0, 24.0]}, 'available_schedules': ['Vakantie', 'Week schema'], 'selected_schedule': 'Week schema', 'last_used': 'Week schema', 'schedule_temperature': 17.0, 'mode': 'auto', 'sensors': {'temperature': 20.1, 'setpoint': 17, 'illuminance': 0.5}}})
2022-03-11 01:39:25 DEBUG (MainThread) [custom_components.plugwise] Finished fetching Anna data in 0.127 seconds (success: True)
2022-03-11 01:39:25 DEBUG (MainThread) [custom_components.plugwise] Add plugwise_notification binary sensor
2022-03-11 01:39:25 DEBUG (MainThread) [custom_components.plugwise] Add outdoor_temperature sensor
2022-03-11 01:39:25 DEBUG (MainThread) [custom_components.plugwise] Add temperature sensor
2022-03-11 01:39:25 DEBUG (MainThread) [custom_components.plugwise] Add illuminance sensor
2022-03-11 01:39:25 DEBUG (MainThread) [custom_components.plugwise] Add setpoint sensor
2022-03-11 01:39:25 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform plugwise
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 782, in add_to_platform_finish
await self.async_added_to_hass()
File "/config/custom_components/plugwise/entity.py", line 77, in async_added_to_hass
self._handle_coordinator_update()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _async_write_ha_state
attr.update(self.state_attributes or {})
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 298, in state_attributes
if self.hvac_action:
File "/config/custom_components/plugwise/climate.py", line 126, in hvac_action
heater_central_data = self.coordinator.data.devices[
KeyError: None
2022-03-11 01:39:25 ERROR (MainThread) [homeassistant.components.climate] Error while setting up plugwise platform for climate
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 782, in add_to_platform_finish
await self.async_added_to_hass()
File "/config/custom_components/plugwise/entity.py", line 77, in async_added_to_hass
self._handle_coordinator_update()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _async_write_ha_state
attr.update(self.state_attributes or {})
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 298, in state_attributes
if self.hvac_action:
File "/config/custom_components/plugwise/climate.py", line 126, in hvac_action
heater_central_data = self.coordinator.data.devices[
KeyError: None
```

**Expected behavior**
a working climate

**Screenshots**
![image](https://user-images.githubusercontent.com/634175/156917918-f1cb81cd-0c69-43c4-8036-aaba0896332b.png)

**Home Assistant (please complete the following information):**
 - Version: `2022.3.x`
 - Deployment: `ubuntu/docker`
 - Installed plugwise version: `plugwise-beta` and `HA-core`
   -  version plugwise-beta: `v0.21.2`
 - Installed through: 
   - `hacs`

**Smile (please complete the following information):**
 - Sort of Smile: `Anna`
 - Firmware: `4.2.1`
 - Hardware: `AME Smile 2.0 board`

***HACS***
- Version: `1.23.0`

**Comment by bouwew** [comment]
How did you install plugwise-beta? Via HACS or another way?

**Comment by bouwew** [comment]
Also, please enable logging for plugwise-beta: in `configuration.yaml` added this:
```
logger:
  default: warn
  logs:
    custom_components.plugwise: debug
    plugwise.smile: debug
```

After adding this, restart HA Core.

After the restart has finished please look in the FULL HOME ASSISTANT LOG, there should be several lines related to plugwise-beta. Please show us the log-message that shows this:
`[custom_components.plugwise] Data: PlugwiseData(gateway={'smile_name': 'Anna' ... `

**Comment by bouwew** [comment]
@Proxx In order to solve this issue, we will need to receive the requested information from you.
If you have any questions related to our requests, please let us know.

**Comment by Proxx** [comment]
sorry for the delay, I reproduced the error with both the standard homeassistant intergration and plugwise-beta (starting around jan-22, currently using a new installation of homeassistant 2022.3.1 with plugwise-beta v0.21.2 (installed with hacs)

I have updated the info accordingly

**Comment by bouwew** [comment]
Thank you. Please also implement the logger-settings on your system as written in message 3, and provide the requested info from the LOGBOEK.

**Comment by Proxx** [comment]
that is the complete log with the setting as you suggested.

PS: one line was missing: `2022-03-11 07:35:52 DEBUG (MainThread) [custom_components.plugwise] DUC update iterval: 0:01:00`

**Comment by bouwew** [comment]
Sorry, I see you added the info in the first post :)

After a quick look I see the heater_id is None, that's unexpected.
To what type of heating system is your Anna connected?

**Comment by Proxx** [comment]
Nefit Proline NxT cw4 with Nefit Opentherm converter

information from plugwise web interface:
Boiler brand: `Bosch Thermotechniek B.V.`
Boiler type: `1.27`
Year: `Unspecified`
Installation date: `Unspecified`
Boiler protocol: `Opentherm`

**Comment by bouwew** [comment]
Ok thanks. That should work I think. But it doesn't.

To be able to troubleshoot this issue, we would like to receive the xml-data from you system.
Please see https://github.com/plugwise/python-plugwise/blob/main/userdata/README.md for instructions on how to do this, scroll down to the Sharing header.
Please email the data to "bouwe" at "westerdijk" point "info".

Any questions, please let us know.

**Comment by bouwew** [comment]
@Proxx Can you please provide the requested information so we can fix this bug?

**Comment by Proxx** [comment]
Wil get the files and send them, sorry for the delay..

**Comment by Proxx** [comment]
they should be in your mailbox

**Comment by bouwew** [comment]
Data received, with thanks!

Looks like there is no `Central heating boiler` present in `/core/appliances`. This causes the error because the Integration expects this one to be there.

More info will follow.

**Comment by Proxx** [comment]
The problem was not caused by plugwise-beta or homeassistant, the problem had to do with a unique situation in the anna where it was functioning on opentherm without any heating configuration loaded in the anna. with the help of @bouwew and the support team of plugwise, the problem has been solved. therefore, I will close this issue.

thanks @bouwew for the dedication and support. and of course the plugwise team
