### ISSUE TITLE
[BUG]: KeyError: 'cooling_state'

### ISSUE THREAD

**Issue by arnoslag** [plugwise/plugwise-beta#272]
### Describe the bug.

hvac is't available, see no temperature in climate.anna entity

### What version of Home Assistant Core has the issue?

2022.4.4

### What was the last working version of Home Assistant Core?

2022.4.4

### What type of installation are you running?

Home Assistant Supervised

### How did you install plugwise-beta?

HACS

### What kind of Plugwise device is having issues?

Smile: Anna

### What firmware version is your Plugwise product at?

 2018-02-08T11:15:53+01:00

### Logging

Logger: homeassistant.components.climate
Source: custom_components/plugwise/climate.py:124
Integration: Klimaat ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 08:42:55 (2 occurrences)
Last logged: 08:42:55

Error adding entities for domain climate with platform plugwise
Error while setting up plugwise platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 798, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/plugwise/entity.py", line 87, in async_added_to_hass
    self._handle_coordinator_update()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 328, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 298, in state_attributes
    if self.hvac_action:
  File "/config/custom_components/plugwise/climate.py", line 124, in hvac_action
    if heater_central_data["binary_sensors"]["cooling_state"]:
KeyError: 'cooling_state'

**Comment by bouwew** [comment]
@arnoslag Which version of Plugwise-beta are you using?

**Comment by arnoslag** [comment]
APR 2022 [0.22.1]

**Comment by bouwew** [comment]
Please upgrade to v0.22.3a1 and test.
You can make this version visible by selecting `Show beta` in HACS.

**Comment by arnoslag** [comment]
thank you, it works again

**Comment by bouwew** [comment]
Great, thanks for reporting back the good result :)
