### ISSUE TITLE
[BUG]: unique_id migration error

### ISSUE THREAD

**Issue by bouwew** [plugwise/plugwise-beta#275]
### Describe the bug.

User ollem reports a `unique_id` migration-error on Gathering of Tweakers.

### What version of Home Assistant Core has the issue?

core-2022.4

### What type of installation are you running?

Home Assistant Core

### How did you install plugwise-beta?

HACS

### What kind of Plugwise device is having issues?

Smile: Anna

### What firmware version is your Plugwise product at?

4.x.y

### Logging

Error setting up entry Adam for plugwise
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/plugwise/__init__.py", line 16, in async_setup_entry
    return await async_setup_entry_gw(hass, entry)
  File "/config/custom_components/plugwise/gateway.py", line 90, in async_setup_entry_gw
    migrate_sensor_entity(hass, coordinator)
  File "/config/custom_components/plugwise/gateway.py", line 180, in migrate_sensor_entity
    ent_reg.async_update_entity(entity_id, new_unique_id=new_unique_id)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 571, in async_update_entity
    raise ValueError(
ValueError: Unique id '0ca13e8176204ca7bf6f09de59f81c83-outdoor_air_temperature' is already in use by 'sensor.opentherm_outdoor_air_temperature'

### Additional information

After removing and re-adding the integration the error is gone.

**Comment by bouwew** [comment]
This issue is stale now, no other users have complained about this --> close.
