### ISSUE TITLE
[BUG]: Unexpected error fetching plugwise data: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by rickstienstra** [plugwise/plugwise-beta#355]
### Describe the bug.

Last weekend we’ve had a new CV-ketel + Plugwise Adam installed. Everything works fine except for the Home Assistant integration. When trying to add the integration, it keeps giving the error ‘Retrying setup: ‘NoneType’ object has no attribute ‘text’’.  This happens with the Core integration, as well with latest (v0.34.7) Custom Component beta installed through HACS.

### What version of Home Assistant Core has the issue?

2023.2.5

### What type of installation are you running?

Home Assistant OS

### How did you install plugwise-beta?

HACS

### What kind of Plugwise device is having issues?

Smile: Adam (including Lisa, Tom, Floor)

### What firmware version is your Plugwise product at?

3.7.3

### Logging

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/components/plugwise/coordinator.py", line 77, in _async_update_data
    await self._connect()
  File "/usr/src/homeassistant/homeassistant/components/plugwise/coordinator.py", line 67, in _connect
    self.api.get_all_devices()
  File "/usr/local/lib/python3.10/site-packages/plugwise/smile.py", line 149, in get_all_devices
    self._all_device_data()
  File "/usr/local/lib/python3.10/site-packages/plugwise/smile.py", line 98, in _all_device_data
    data = self._get_device_data(device_id)
  File "/usr/local/lib/python3.10/site-packages/plugwise/smile.py", line 274, in _get_device_data
    device_data = self._get_appliance_data(dev_id)
  File "/usr/local/lib/python3.10/site-packages/plugwise/helper.py", line 1022, in _get_appliance_data
    self._get_toggle_state(appliance, toggle, name, data)
  File "/usr/local/lib/python3.10/site-packages/plugwise/helper.py", line 1482, in _get_toggle_state
    data.update({name: item.find("state").text == "on"})
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by rickstienstra** [comment]
After resetting internet for the like 20+ time, somehow the plugin started working. Weird but works now!

**Comment by bouwew** [comment]
@rickstienstra you mean resetting the Adam made it work again?

**Comment by rickstienstra** [comment]
@bouwew I've resetted the Adam through the web interface. But it might've been an issue with our network, because I've also resetted our modem a few minutes before this. Every sensor gets picked up by HA and is working!

**Comment by bouwew** [comment]
I'm asking because the error you show above points to a missing key in the Adam's database. By resetting the Adam or by making a change in a related Adam-setting, this error can be solved.

Anyway, if it's working for you with plugwise-beta, you can also switch back to HA Plugwise, that integration should now work too.
