### ISSUE TITLE
[TODO]: Download diagnostics is not working

### ISSUE THREAD

**Issue by mvdwetering** [plugwise/plugwise-beta#375]
### Todo

Not really a todo, more like a bug, but there is no bug issue type.

When trying to use the "Download diagnostics" option from Home Assistant for the plugwise beta integration it just fails. I see this error below in the logs.

![image](https://user-images.githubusercontent.com/732514/230732741-c7f2aafc-a2e2-48f4-b897-a6901c9c20ea.png)

```
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/plugwise/diagnostics.py:18
Integration: Plugwise Beta (documentation)
First occurred: 18:34:18 (1 occurrences)
Last logged: 18:34:18

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/diagnostics/__init__.py", line 246, in get
    data = await info.config_entry_diagnostics(hass, config_entry)
  File "/config/custom_components/plugwise/diagnostics.py", line 18, in async_get_config_entry_diagnostics
    coordinator: PlugwiseDataUpdateCoordinator = hass.data[DOMAIN][entry.entry_id][
KeyError: 'coordinator'
```

**Comment by bouwew** [comment]
Good point, the diagnostics-function only works for the Smile's.

**Comment by CoMPaTech** [comment]
The `bug` issue template was broken unfortunately (fixed), changed title accordingly
