### ISSUE TITLE
[BUG]: UnboundLocalError: cannot access local variable 'tmp_setpoint_low' where it is not associated with a value

### ISSUE THREAD

**Issue by bouwew** [plugwise/plugwise-beta#425]
### Describe the bug.

User H. Mengerink reports a problem when using the climate.set_temperature service.

### What version of Plugwise Beta are you using?

v0.34.11a4

### What was the last working version of Plugwise Beta (or Core if not using beta before)?

Unknown

### What version of Home Assistant Core are you using?

core-2023.6.2

### What type of installation are you running?

Home Assistant Supervised

### How did you install plugwise-beta?

HACS

### What kind of Plugwise device is having issues?

Smile: Adam (including Lisa, Tom, Floor) connected to a Loria heatpump with cooling capabilities.

### What firmware version is your Plugwise product at?

Unknown

### Additional information

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/plugwise/climate.py:197
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 21:43:21 (1 occurrences)
Last logged: 21:43:21

[547839536720] Error handling message: Unknown error (unknown_error) Hans Mengerink from 192.168.2.52 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/[113.0.0.0](http://113.0.0.0/) Safari/537.36)

Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response

    await func(hass, connection, msg)

  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 678, in handle_execute_script

    await script_obj.async_run(msg.get("variables"), context=context)

  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1533, in async_run

    await asyncio.shield(run.async_run())

  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 410, in async_run

    await self._async_step(log_exceptions=False)

  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 454, in _async_step

    self._handle_exception(

  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 477, in _handle_exception

    raise exception

  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 452, in _async_step

    await getattr(self, handler)()

  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 685, in _async_call_service_step

    await service_task

  File "/usr/src/homeassistant/homeassistant/core.py", line 1910, in async_call

    task.result()

  File "/usr/src/homeassistant/homeassistant/core.py", line 1950, in _execute_service

    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(

  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service

    await service.entity_service_call(

  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 811, in entity_service_call

    future.result()  # pop exception if have

    ^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1034, in async_request_call

    await coro

  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 851, in _handle_entity_call

    await result

  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 613, in async_service_temperature_set

    await entity.async_set_temperature(**kwargs)

  File "/config/custom_components/plugwise/util.py", line 30, in handler

    return await func(self, *args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/config/custom_components/plugwise/climate.py", line 197, in async_set_temperature

    await self.coordinator.api.set_temperature(self.device["location"], data)

  File "/usr/local/lib/python3.11/site-packages/plugwise/__init__.py", line 695, in set_temperature

    setpoint = tmp_setpoint_low

               ^^^^^^^^^^^^^^^^

UnboundLocalError: cannot access local variable 'tmp_setpoint_low' where it is not associated with a value
```
This error happens when doing this:
![image](https://github.com/plugwise/plugwise-beta/assets/11290930/f3542483-88d6-4cb1-ab7a-1d04d15725da)

**Comment by bouwew** [comment]
Enhancement covering this error-occurrence added to the plugwise backend library.
